### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mistakevin** [AustinCodingAcademy/frontend-intermediate-workbook#3]
- [x] Apps
  - [x] Pig Latin Generator
  - [x] Rock Paper Scissors
  - [x] Tic Tac Toe
  - [x] Towers of Hanoi
  - [x] Mastermind
  - [x] Checkers
  - [x] Tic Tac Toe (jQuery)
  - [x] Towers of Hanoi (jQuery)
  - [x] Todo (jQuery)
  - [x] Business Cards (jQuery/AJAX)
  - [x] Gist Blog

- [ ] CodeWars Katas
  - [x] Kata Zero
  - [x] Kata One
  - [x] Kata Two
  - [ ] Kata Three
  - [ ] Kata Four
  - [ ] Kata Five
  - [ ] Kata Six
  - [ ] Kata Seven
  - [ ] Kata Eight
  - [ ] Kata Nine
  - [ ] Kata Ten

- [x] Project Euler Problems
  - [x] Problem Zero
  - [x] Problem One
  - [x] Problem Two
  - [x] Problem Three
  - [x] Problem Four
  - [x] Problem Five
  - [x] Problem Six
  - [x] Problem Seven
  - [x] Problem Eight
  - [x] Problem Nine
  - [x] Problem Ten

- [x] Tests
  - [x] Lesson Zero - `return`
  - [x] Lesson One - Booleans, Comparisons
  - [x] Lesson Two - Conditionals
  - [x] Lesson Three - Arrays
  - [x] Lesson Four - Arrays, Objects
  - [x] Lesson Five - Loops
  - [x] Lesson Six - Objects Oriented Programming (Car Example)
